/**
 * The credential every spec sends, and the header spread that carries it.
 *
 * **`Support/` is where this belongs**, by the rule `vitest.config.ts` states: the directory holds the
 * things with no counterpart in `src/`. The token is a property of the *harness* — a value that exists
 * so the suite can get past a gate — rather than anything the Worker exports, and it is deliberately
 * not a constant in `src/` that a spec imports.
 *
 * **This is not a secret and must not be mistaken for one.** It is a fixture, written in the clear in
 * a committed file, and it is what `vitest.config.ts` binds as `SYNC_API_TOKEN` for the test runtime.
 * A real deployment's secret is generated by its operator, lives in `backend/.dev.vars` and
 * `wrangler secret put`, and appears nowhere in this repository — see `README.md` § The backend.
 *
 * **This file must import nothing.** `vitest.config.ts` imports `TEST_API_TOKEN` from here, and that
 * config is loaded by the Node side of the pool and typechecked by `tsconfig.node.json` — so an
 * import of `cloudflare:test`, or of anything under `src/`, would drag a `workerd`-only module into a
 * Node module graph and fail before a single test ran. Keep it a leaf.
 */

/**
 * The value the test runtime is configured to accept.
 *
 * Long enough to clear `MIN_TOKEN_LENGTH` — deliberately, because a fixture below the floor would
 * exercise `createApp`'s *unarmed* arm on every request in the suite and every spec would answer
 * `500`. The length is not incidental to the fixture working; it is the reason this string is 44
 * characters and not `"test"`.
 */
export const TEST_API_TOKEN = "test-token-not-a-secret-0000000000000000000";

/**
 * The headers a request needs to reach a route: the gate's credential, and optionally an identity.
 *
 * **A spread rather than a `Headers` object**, because every call site in this suite already builds a
 * plain literal — `{ "content-type": "application/json", … }` — and the smallest change to twenty-odd
 * local helpers is the one that cannot be got wrong in a way the suite would not notice. Each helper
 * keeps its own resource-specific parts and adds `...authHeaders(userId)`.
 *
 * **The token is always sent, including by the specs that assert a `400`.** That is the point rather
 * than an oversight: those tests are about the *identity* header — missing, empty, too short, too long
 * — and the gate deliberately runs before the identity schema does. Without a valid token they would
 * get a `401` and pass for entirely the wrong reason, which would delete the only wire-level evidence
 * that `MIN_KEY_LENGTH` and `MAX_KEY_LENGTH` are enforced at all.
 *
 * `userId` is omitted rather than defaulted, so a caller that wants to send *no* identity header can
 * say so; passing `undefined` explicitly is the same thing and reads better at a call site that is
 * about a missing header.
 */
export function authHeaders(userId?: string): Record<string, string> {
  const headers: Record<string, string> = {
    authorization: `Bearer ${TEST_API_TOKEN}`,
  };

  if (userId !== undefined) headers["x-whoopsy-user-id"] = userId;

  return headers;
}
